name: concha
description: "Concha — hear it again. sing it better."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.9

environment:
  sdk: ^3.10.8
dependencies:
  flutter:
    sdk: flutter

  audio_metadata_reader: ^1.4.2
  flutter_soloud: ^3.5.0

  animations: ^2.1.1
  styled_widget: ^0.4.1
  file_selector: ^1.1.0
  flutter_lyric: ^3.0.2
  nested: ^1.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

  path_provider: ^2.1.5
  path: ^1.9.1
  json_annotation: ^4.11.0
  uuid: ^4.5.1
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  http: ^1.6.0
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: assets/icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/icon.png
