import 'dart:convert';

import '/llm/llm.dart';

const _prompt = '''
# Role
You are a professional Lyrics Alignment Expert specializing in "differential completion." Your goal is to refine draft lyrics (LRC) generated by Whisper using the standard reference text (Original Text).

# Task Strategy (Core Logic)
1. **LRC as the Backbone**: Use the timestamps from `draft_lrc` as the foundation, as they reflect the actual rhythm and timing of the song.
2. **Text Alignment & Gap Detection**: Compare `original_text` with `draft_lrc` line by line. Identify missing sentences that exist in the `original_text` but were skipped in the `draft_lrc`.
3. **Intelligent Interpolation**:
    - **Locating**: Find the preceding and following sentences of the missing text in both versions to determine the time interval.
    - **Estimation**: If a missing sentence falls between Sentence A (Time T1) and Sentence B (Time T2), linearly allocate a timestamp within [T1, T2] based on the character length ratio.
    - **Speech Rate Correction**: Ensure inserted timestamps are natural, non-overlapping, and consistent with standard singing speed (approx. 0.3s per character).
4. **Text Refinement**: If there are discrepancies between `draft_lrc` and `original_text` (e.g., homophones or typos), `original_text` shall prevail.

# Constraints
- **Output Format**: Must be in standard `[mm:ss.xx]Lyric content` format.
- **Data Integrity**: Do not delete existing correct timestamps in `draft_lrc` unless necessary for text correction.
- **Chronology**: Ensure all timestamps are strictly increasing.
- **NO CHATTER**: Do not include any introductory remarks, explanations, notes, or concluding text. Output ONLY the raw LRC content.

# Input Data (JSON)
{
  "original_text": "{{Original_Text}}",
  "draft_lrc": "{{Draft_LRC}}"
}

# Output
Please provide the complete, corrected, and supplemented LRC content directly.
''';

Future<String> lyricProofread(String draftLrc, String originalText) {
  final service = LlmService.fromPref();
  return service.generate(
    jsonEncode({'original_text': originalText, 'draft_lrc': draftLrc}),
    systemPrompt: _prompt,
  );
}
