name: Upload assets

on:
  release:
    types: [published]

jobs:
  build:
    name: Build app and upload artifacts
    uses: joodo/concha/.github/workflows/build.yml@main
    secrets: inherit

  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.build.outputs.workflow_id }}
          path: release-assets
          merge-multiple: true

      - name: Upload release binaries
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} release-assets/*
